fastlane_version "2.11.0"
default_platform :ios


platform :ios do
  before_all do
    cocoapods
  end

  desc "Builds and runs all tests on an iPhone 📱"
  lane :test do
    scan(
      scheme: "C7FIT", 
      devices: ["iPhone 7"]
    )
  end

  desc "Lints all Swift files to ensure consistent style 💯"
  desc "Results are saved to fastlane/test_output/swiftlint.result.json"
  lane :lint do
    swiftlint(
      mode: :lint,
      output_file: "fastlane/test_output/swiftlint.result.html",
      reporter: "html"
    )
  end

  desc "Uses synx to reorganize Xcode project folder to match Xcode groups"
  lane :synx do
    # Synx can sometimes confuse cocoapods, so we run it afterwards
    sh "synx --no-sort-by-name ../SeedAnalysis.xcodeproj"
    cocoapods
  end
end
